### ISSUE TITLE
Wait for DNS propagation

### ISSUE THREAD

**Issue by branfts** [branfts/ai#10]
Link should not show ready until DNS is ready. It's a bug.

![image](https://github.com/user-attachments/assets/deb5f736-9972-404b-8d68-e9ec4146d2b9)

**Comment by branfts** [comment]
Not sure why it's coming back early...

https://github.com/branfts/ai/blob/main/src/views/Home.vue#L87-L99

**Comment by june07** [comment]
fixed: https://github.com/branfts/ai/commit/bd55ed86a144be77f3fc2d2e8526c893108bb6aa#r144615836
